appName: vote
replicaCount: 1

image:
  repository: dockersamples/examplevotingapp_vote
  tag: latest

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 31000

env:
  - name: FLASK_ENV
    value: development
  - name: ENVIRONMENT
    value: dev
  - name: LOG_LEVEL
    value: DEBUG