appName: db
replicaCount: 1

image:
  repository: postgres
  tag: "15-alpine"

service:
  type: ClusterIP
  port: 5432
  targetPort: 5432

env:
  - name: POSTGRES_USER
    value: postgres
  - name: POSTGRES_PASSWORD
    value: postgres
  - name: POSTGRES_DB
    value: votes